In [1]:
import pandas as pd

Učitavanje dataseta

In [3]:
df = pd.read_csv("apple_products.csv")

In [4]:
df

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB
...,...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,4 GB

Prikazati prvih 5 redova dataseta

metoda za prikaz prvih 5 redova - po defaultu

In [5]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [6]:
df.head(10)

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB
5,"APPLE iPhone 8 Plus (Silver, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,49900,49900,0,3431,356,MOBEXRGVQGYYP8FV,4.6,2 GB
6,"APPLE iPhone 8 Plus (Space Grey, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,49900,49900,0,3431,356,MOBEXRGVQKBREZP8,4.6,2 GB
7,"APPLE iPhone 8 (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-space-...,Apple,77000,77000,0,11202,794,MOBEXRGVZFZGZEWV,4.5,2 GB
8,"APPLE iPhone XS Max (Silver, 64 GB)",https://www.flipkart.com/apple-iphone-xs-max-s...,Apple,89900,89900,0,1454,149,MOBF944E2XAHW8V5,4.6,4 GB
9,"Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...",https://www.flipkart.com/apple-iphone-xr-produ...,Apple,41999,52900,20,79512,6796,MOBF9Z7ZHQC23PWQ,4.6,4 GB

Prikazati zadnjih 5 redova dataseta

In [7]:
df.tail()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,4 GB

Brisanje kolone

In [8]:
del df['Product URL']

In [9]:
df

,Product Name,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",Apple,46999,54900,14,43470,3331,MOBFWQ6BTFFJKGKE,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",Apple,46999,54900,14,43470,3331,MOBFWQ6BVWVEH3XE,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",Apple,46999,54900,14,43470,3331,MOBFWQ6BXGJCEYNY,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",Apple,46999,54900,14,43470,3331,MOBFWQ6BYYV3FCU7,4.6,4 GB

In [10]:
del df["Upc"]

In [12]:
df

,Product Name,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",Apple,49900,49900,0,3431,356,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",Apple,84900,84900,0,3431,356,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",Apple,84900,84900,0,3431,356,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",Apple,77000,77000,0,11202,794,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",Apple,77000,77000,0,11202,794,4.5,2 GB
...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",Apple,29999,39900,24,95909,8161,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",Apple,46999,54900,14,43470,3331,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",Apple,46999,54900,14,43470,3331,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",Apple,46999,54900,14,43470,3331,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",Apple,46999,54900,14,43470,3331,4.6,4 GB

Ispis svih kolona

In [13]:
lista_kolona = list(df.columns)

lista_kolona

['Product Name',
 'Brand',
 'Sale Price',
 'Mrp',
 'Discount Percentage',
 'Number Of Ratings',
 'Number Of Reviews',
 'Star Rating',
 'Ram']

Smještanje imena kolona u listu

In [14]:
df.values

array([['APPLE iPhone 8 Plus (Gold, 64 GB)', 'Apple', 49900, 49900, 0,
        3431, 356, 4.6, '2 GB'],
       ['APPLE iPhone 8 Plus (Space Grey, 256 GB)', 'Apple', 84900,
        84900, 0, 3431, 356, 4.6, '2 GB'],
       ['APPLE iPhone 8 Plus (Silver, 256 GB)', 'Apple', 84900, 84900, 0,
        3431, 356, 4.6, '2 GB'],
       ['APPLE iPhone 8 (Silver, 256 GB)', 'Apple', 77000, 77000, 0,
        11202, 794, 4.5, '2 GB'],
       ['APPLE iPhone 8 (Gold, 256 GB)', 'Apple', 77000, 77000, 0, 11202,
        794, 4.5, '2 GB'],
       ['APPLE iPhone 8 Plus (Silver, 64 GB)', 'Apple', 49900, 49900, 0,
        3431, 356, 4.6, '2 GB'],
       ['APPLE iPhone 8 Plus (Space Grey, 64 GB)', 'Apple', 49900, 49900,
        0, 3431, 356, 4.6, '2 GB'],
       ['APPLE iPhone 8 (Space Grey, 256 GB)', 'Apple', 77000, 77000, 0,
        11202, 794, 4.5, '2 GB'],
       ['APPLE iPhone XS Max (Silver, 64 GB)', 'Apple', 89900, 89900, 0,
        1454, 149, 4.6, '4 GB'],
       ['Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includes EarPods, Power Adapter)',
        'Apple', 41999, 52900, 20, 79512, 6796, 4.6, '4 GB'],
       ['Apple iPhone XR (Black, 64 GB) (Includes EarPods, Power Adapter)',
        'Apple', 39999, 47900, 16, 79512, 6796, 4.6, '4 GB'],
       ['Apple iPhone XR (Coral, 128 GB) (Includes EarPods, Power Adapter)',
        'Apple', 41999, 52900, 20, 79582, 6804, 4.6, '4 GB'],
       ['Apple iPhone XR (Black, 128 GB) (Includes EarPods, Power Adapter)',
        'Apple', 41999, 52900, 20, 79512, 6796, 4.6, '3 GB'],
       ['Apple iPhone XR (White, 128 GB) (Includes EarPods, Power Adapter)',
        'Apple', 41999, 52900, 20, 79512, 6796, 4.6, '4 GB'],
       ['APPLE iPhone 11 Pro Max (Gold, 256 GB)', 'Apple', 131900,
        131900, 0, 1078, 101, 4.7, '4 GB'],
       ['APPLE iPhone 11 Pro Max (Gold, 64 GB)', 'Apple', 117100, 117100,
        0, 1078, 101, 4.7, '4 GB'],
       ['APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)', 'Apple',
        131900, 131900, 0, 1078, 101, 4.7, '4 GB'],
       ['APPLE iPhone 11 Pro Max (Space Grey, 64 GB)', 'Apple', 117100,
        117100, 0, 1078, 101, 4.7, '4 GB'],
       ['APPLE iPhone 11 Pro (Midnight Green, 64 GB)', 'Apple', 74999,
        106600, 29, 7088, 523, 4.6, '4 GB'],
       ['APPLE iPhone 11 Pro (Space Grey, 512 GB)', 'Apple', 117900,
        140300, 15, 7088, 523, 4.6, '4 GB'],
       ['APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)', 'Apple',
        117100, 117100, 0, 1078, 101, 4.7, '4 GB'],
       ['APPLE iPhone 11 Pro (Midnight Green, 512 GB)', 'Apple', 117900,
        140300, 15, 7088, 523, 4.6, '4 GB'],
       ['APPLE iPhone 11 Pro (Space Grey, 256 GB)', 'Apple', 99900,
        121300, 17, 7081, 522, 4.6, '4 GB'],
       ['Apple iPhone SE (White, 256 GB) (Includes EarPods, Power Adapter)',
        'Apple', 44999, 54900, 18, 95909, 8161, 4.5, '2 GB'],
       ['APPLE iPhone 12 Pro (Silver, 512 GB)', 'Apple', 140900, 149900,
        6, 542, 42, 4.5, '4 GB'],
       ['APPLE iPhone 12 Pro Max (Pacific Blue, 256 GB)', 'Apple',
        130900, 139900, 6, 580, 45, 4.6, '6 GB'],
       ['APPLE iPhone 12 Mini (White, 128 GB)', 'Apple', 64900, 74900,
        13, 740, 64, 4.5, '4 GB'],
       ['APPLE iPhone 12 Pro (Graphite, 256 GB)', 'Apple', 120900,
        129900, 6, 545, 42, 4.5, '6 GB'],
       ['APPLE iPhone 12 Mini (White, 64 GB)', 'Apple', 59900, 69900, 14,
        740, 64, 4.5, '4 GB'],
       ['APPLE iPhone 12 (White, 128 GB)', 'Apple', 75900, 84900, 10,
        2101, 180, 4.6, '6 GB'],
       ['APPLE iPhone 12 Pro (Graphite, 128 GB)', 'Apple', 110900,
        119900, 7, 545, 42, 4.5, '6 GB'],
       ['APPLE iPhone 12 Pro Max (Graphite, 256 GB)', 'Apple', 130900,
        139900, 6, 580, 45, 4.6, '6 GB'],
       ['APPLE iPhone 12 Pro Max (Graphite, 128 GB)', 'Apple', 120900,
        129900, 6, 580, 45, 4.6, '6 GB'],
       ['APPLE iPhone 12 Mini (Black, 128 GB)', 'Apple', 64900, 74900,
        13, 730, 63, 4.5, '4 GB'],
       ['APPLE iPhone 12 Mini (Blue, 128 GB)', 'Apple', 64900, 74900, 13,
        730, 63, 4.5, '4 GB'],
       ['APPLE iPhone 12 (Black, 128 GB)', 'Apple', 75900, 84900, 10,
        2101, 180, 4.6, '6 GB'],
       ['APPLE iPhone 12 (Blue, 128 GB)', 'Apple', 75900, 84900, 10,
        2101, 180, 4.6, '6 GB'],
       ['APPLE iPhone 12 Pro Max (Silver, 128 GB)', 'Apple', 120900,
        129900, 6, 580, 45, 4.6, '6 GB'],
       ['APPLE iPhone 12 Mini (Red, 64 GB)', 'Apple', 59900, 69900, 14,
        740, 64, 4.5, '6 GB'],
       ['APPLE iPhone 12 Pro Max (Gold, 128 GB)', 'Apple', 120900,
        129900, 6, 580, 45, 4.6, '6 GB'],
       ['APPLE iPhone 12 (Green, 128 GB)', 'Apple', 75900, 84900, 10,
        2092, 178, 4.6, '6 GB'],
       ['APPLE iPhone 12 Pro (Pacific Blue, 512 GB)', 'Apple', 140900,
        149900, 6, 545, 42, 4.5, '4 GB'],
       ['APPLE iPhone 12 (White, 64 GB)', 'Apple', 70900, 79900, 11,
        2101, 180, 4.6, '6 GB'],
       ['APPLE iPhone 12 (Black, 64 GB)', 'Apple', 70900, 79900, 11,
        2092, 178, 4.6, '6 GB'],
       ['APPLE iPhone 12 (Red, 128 GB)', 'Apple', 75900, 84900, 10, 2101,
        180, 4.6, '6 GB'],
       ['APPLE iPhone 12 Mini (Black, 64 GB)', 'Apple', 59900, 69900, 14,
        740, 64, 4.5, '4 GB'],
       ['APPLE iPhone 12 Pro (Pacific Blue, 128 GB)', 'Apple', 110900,
        119900, 7, 545, 42, 4.5, '6 GB'],
       ['APPLE iPhone 12 Pro Max (Pacific Blue, 128 GB)', 'Apple',
        120900, 129900, 6, 580, 45, 4.6, '6 GB'],
       ['APPLE iPhone 12 Pro Max (Silver, 256 GB)', 'Apple', 130900,
        139900, 6, 580, 45, 4.6, '6 GB'],
       ['APPLE iPhone 12 Pro Max (Gold, 256 GB)', 'Apple', 130900,
        139900, 6, 580, 45, 4.6, '6 GB'],
       ['APPLE iPhone 11 (White, 128 GB)', 'Apple', 54999, 59900, 8,
        43707, 3357, 4.6, '4 GB'],
       ['APPLE iPhone 11 (Red, 128 GB)', 'Apple', 54999, 59900, 8, 43707,
        3357, 4.6, '4 GB'],
       ['APPLE iPhone SE (White, 64 GB)', 'Apple', 29999, 39900, 24,
        95807, 8154, 4.5, '2 GB'],
       ['APPLE iPhone SE (Black, 128 GB)', 'Apple', 34999, 44900, 22,
        95909, 8161, 4.5, '2 GB'],
       ['APPLE iPhone SE (White, 128 GB)', 'Apple', 34999, 44900, 22,
        95807, 8154, 4.5, '2 GB'],
       ['APPLE iPhone SE (Red, 128 GB)', 'Apple', 34999, 44900, 22,
        95909, 8161, 4.5, '2 GB'],
       ['APPLE iPhone 11 (Black, 128 GB)', 'Apple', 54999, 59900, 8,
        43470, 3331, 4.6, '4 GB'],
       ['APPLE iPhone SE (Black, 64 GB)', 'Apple', 29999, 39900, 24,
        95909, 8161, 4.5, '4 GB'],
       ['APPLE iPhone 11 (Purple, 64 GB)', 'Apple', 46999, 54900, 14,
        43470, 3331, 4.6, '4 GB'],
       ['APPLE iPhone 11 (White, 64 GB)', 'Apple', 46999, 54900, 14,
        43470, 3331, 4.6, '4 GB'],
       ['APPLE iPhone 11 (Black, 64 GB)', 'Apple', 46999, 54900, 14,
        43470, 3331, 4.6, '4 GB'],
       ['APPLE iPhone 11 (Red, 64 GB)', 'Apple', 46999, 54900, 14, 43470,
        3331, 4.6, '4 GB']], dtype=object)

Ispis svih vrijednosti

Provjera jedinstvenih vrijednosti za kolonu Brand i Ram

In [18]:

df['Brand'].unique()

array(['Apple'], dtype=object)

In [19]:
df['Ram'].unique()

array(['2 GB', '4 GB', '3 GB', '6 GB'], dtype=object)

Provjeriti da li se u datasetu nalazi 'APPLE iPhone 11 (Black, 64 GB)' i Number of Reviews = 8161

In [29]:
df.isin(['APPLE iPhone 11 (Black, 64 GB)'])

,Product Name,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Star Rating,Ram
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
57,False,False,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False
60,True,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False,False

In [28]:
df.isin([8161])

,Product Name,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Star Rating,Ram
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
57,False,False,False,False,False,False,True,False,False
58,False,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False
60,False,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False,False

Provjera da li ima NaN vrijednostu u Mrp koloni, i ako ima koliko ih ima

In [30]:
df.isnull()

,Product Name,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Star Rating,Ram
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
57,False,False,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False
60,False,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False,False

### Filtriranje

Ispisati sve redove iz dataseta koji imaju Discount Percentage veći od 20%

In [34]:
df[df['Discount Percentage']>20]

,Product Name,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Star Rating,Ram
18,"APPLE iPhone 11 Pro (Midnight Green, 64 GB)",Apple,74999,106600,29,7088,523,4.6,4 GB
52,"APPLE iPhone SE (White, 64 GB)",Apple,29999,39900,24,95807,8154,4.5,2 GB
53,"APPLE iPhone SE (Black, 128 GB)",Apple,34999,44900,22,95909,8161,4.5,2 GB
54,"APPLE iPhone SE (White, 128 GB)",Apple,34999,44900,22,95807,8154,4.5,2 GB
55,"APPLE iPhone SE (Red, 128 GB)",Apple,34999,44900,22,95909,8161,4.5,2 GB
57,"APPLE iPhone SE (Black, 64 GB)",Apple,29999,39900,24,95909,8161,4.5,4 GB

Naći sumu cijena "Sale Price" za produkte koji imaju Discount Percentage veći od 20%

In [43]:
lista = []
if [df[df['Discount Percentage']>20]]:
    lista = df['Sale Price']

lista
sum(lista)

4964581

Provjeriti da li je Mrp sa Discount Percentage veći od Sale Price

In [44]:
df[df['Mrp'] > df['Sale Price']]

,Product Name,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Star Rating,Ram
9,"Apple iPhone XR ((PRODUCT)RED, 128 GB) (Includ...",Apple,41999,52900,20,79512,6796,4.6,4 GB
10,"Apple iPhone XR (Black, 64 GB) (Includes EarPo...",Apple,39999,47900,16,79512,6796,4.6,4 GB
11,"Apple iPhone XR (Coral, 128 GB) (Includes EarP...",Apple,41999,52900,20,79582,6804,4.6,4 GB
12,"Apple iPhone XR (Black, 128 GB) (Includes EarP...",Apple,41999,52900,20,79512,6796,4.6,3 GB
13,"Apple iPhone XR (White, 128 GB) (Includes EarP...",Apple,41999,52900,20,79512,6796,4.6,4 GB
18,"APPLE iPhone 11 Pro (Midnight Green, 64 GB)",Apple,74999,106600,29,7088,523,4.6,4 GB
19,"APPLE iPhone 11 Pro (Space Grey, 512 GB)",Apple,117900,140300,15,7088,523,4.6,4 GB
21,"APPLE iPhone 11 Pro (Midnight Green, 512 GB)",Apple,117900,140300,15,7088,523,4.6,4 GB
22,"APPLE iPhone 11 Pro (Space Grey, 256 GB)",Apple,99900,121300,17,7081,522,4.6,4 GB
23,"Apple iPhone SE (White, 256 GB) (Includes EarP...",Apple,44999,54900,18,95909,8161,4.5,2 GB
24,"APPLE iPhone 12 Pro (Silver, 512 GB)",Apple,140900,149900,6,542,42,4.5,4 GB
25,"APPLE iPhone 12 Pro Max (Pacific Blue, 256 GB)",Apple,130900,139900,6,580,45,4.6,6 GB
26,"APPLE iPhone 12 Mini (White, 128 GB)",Apple,64900,74900,13,740,64,4.5,4 GB
27,"APPLE iPhone 12 Pro (Graphite, 256 GB)",Apple,120900,129900,6,545,42,4.5,6 GB
28,"APPLE iPhone 12 Mini (White, 64 GB)",Apple,59900,69900,14,740,64,4.5,4 GB
29,"APPLE iPhone 12 (White, 128 GB)",Apple,75900,84900,10,2101,180,4.6,6 GB
30,"APPLE iPhone 12 Pro (Graphite, 128 GB)",Apple,110900,119900,7,545,42,4.5,6 GB
31,"APPLE iPhone 12 Pro Max (Graphite, 256 GB)",Apple,130900,139900,6,580,45,4.6,6 GB
32,"APPLE iPhone 12 Pro Max (Graphite, 128 GB)",Apple,120900,129900,6,580,45,4.6,6 GB
33,"APPLE iPhone 12 Mini (Black, 128 GB)",Apple,64900,74900,13,730,63,4.5,4 GB
34,"APPLE iPhone 12 Mini (Blue, 128 GB)",Apple,64900,74900,13,730,63,4.5,4 GB
35,"APPLE iPhone 12 (Black, 128 GB)",Apple,75900,84900,10,2101,180,4.6,6 GB
36,"APPLE iPhone 12 (Blue, 128 GB)",Apple,75900,84900,10,2101,180,4.6,6 GB
37,"APPLE iPhone 12 Pro Max (Silver, 128 GB)",Apple,120900,129900,6,580,45,4.6,6 GB
38,"APPLE iPhone 12 Mini (Red, 64 GB)",Apple,59900,69900,14,740,64,4.5,6 GB
39,"APPLE iPhone 12 Pro Max (Gold, 128 GB)",Apple,120900,129900,6,580,45,4.6,6 GB
40,"APPLE iPhone 12 (Green, 128 GB)",Apple,75900,84900,10,2092,178,4.6,6 GB
41,"APPLE iPhone 12 Pro (Pacific Blue, 512 GB)",Apple,140900,149900,6,545,42,4.5,4 GB
42,"APPLE iPhone 12 (White, 64 GB)",Apple,70900,79900,11,2101,180,4.6,6 GB
43,"APPLE iPhone 12 (Black, 64 GB)",Apple,70900,79900,11,2092,178,4.6,6 GB
44,"APPLE iPhone 12 (Red, 128 GB)",Apple,75900,84900,10,2101,180,4.6,6 GB
45,"APPLE iPhone 12 Mini (Black, 64 GB)",Apple,59900,69900,14,740,64,4.5,4 GB
46,"APPLE iPhone 12 Pro (Pacific Blue, 128 GB)",Apple,110900,119900,7,545,42,4.5,6 GB
47,"APPLE iPhone 12 Pro Max (Pacific Blue, 128 GB)",Apple,120900,129900,6,580,45,4.6,6 GB
48,"APPLE iPhone 12 Pro Max (Silver, 256 GB)",Apple,130900,139900,6,580,45,4.6,6 GB
49,"APPLE iPhone 12 Pro Max (Gold, 256 GB)",Apple,130900,139900,6,580,45,4.6,6 GB
50,"APPLE iPhone 11 (White, 128 GB)",Apple,54999,59900,8,43707,3357,4.6,4 GB
51,"APPLE iPhone 11 (Red, 128 GB)",Apple,54999,59900,8,43707,3357,4.6,4 GB
52,"APPLE iPhone SE (White, 64 GB)",Apple,29999,39900,24,95807,8154,4.5,2 GB
53,"APPLE iPhone SE (Black, 128 GB)",Apple,34999,44900,22,95909,8161,4.5,2 GB
54,"APPLE iPhone SE (White, 128 GB)",Apple,34999,44900,22,95807,8154,4.5,2 GB
55,"APPLE iPhone SE (Red, 128 GB)",Apple,34999,44900,22,95909,8161,4.5,2 GB
56,"APPLE iPhone 11 (Black, 128 GB)",Apple,54999,59900,8,43470,3331,4.6,4 GB
57,"APPLE iPhone SE (Black, 64 GB)",Apple,29999,39900,24,95909,8161,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",Apple,46999,54900,14,43470,3331,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",Apple,46999,54900,14,43470,3331,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",Apple,46999,54900,14,43470,3331,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",Apple,46999,54900,14,43470,3331,4.6,4 GB